class Error(Exception): ...
class PageRelatedError(Error): ...
class PageSaveRelatedError(PageRelatedError): ...
class EditConflict(PageSaveRelatedError): ...
class NoPage(PageRelatedError): ...
class UserRightsError(Error): ...
class HiddenKeyError(UserRightsError, KeyError): ...
